# Generated by Django 5.1.15 on 2026-09-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='Unique OPIS Truckstop ID', unique=True)),
                ('name', models.CharField(help_text='Truckstop brand or name', max_length=200)),
                ('address', models.CharField(help_text='Street address / highway exit', max_length=300)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(db_index=True, help_text='2-letter US state code', max_length=2)),
                ('retail_price', models.DecimalField(decimal_places=4, help_text='Retail fuel price per gallon (USD)', max_digits=7)),
                ('latitude', models.FloatField(db_index=True, help_text='WGS84 Latitude')),
                ('longitude', models.FloatField(db_index=True, help_text='WGS84 Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'db_table': 'api_fuelstation',
                'indexes': [models.Index(fields=['state', 'retail_price'], name='api_fuelsta_state_c0ca60_idx'), models.Index(fields=['latitude', 'longitude'], name='api_fuelsta_latitud_a8079e_idx')],
            },
        ),
    ]
